### ISSUE TITLE
Moverelative stage fails with only one joint offset entry in setDirection()

### ISSUE THREAD

**Issue by karolyartur** [ros-planning/moveit_task_constructor#130]
While experimenting with the Python API's demo, [cartesian.py](https://github.com/ros-planning/moveit_task_constructor/blob/wip-python-api/demo/scripts/cartesian.py) I found that in the `"joint offset"` stage if a dictionary containing a single entry (e.g. `dict(panda_joint1=pi/6)`) is passed to the `setDirection` function, the stage results in a failed solution attempt.

This also happens when I check out master branch, change the corresponding line (103) in `cartesian.cpp` so it offsets just one joint, build and try to run that code.

For both the Python and the C++ demos I used the scene from `moveit_task_constructor_demo demo.launch` for testing.

**Comment by rhaschke** [comment]
The problem is not related to the single dict entry, but to an IK problem: Looks like along the straight line towards the goal posture, the robot runs into a singularity, which is why the stage fails.
Changing the joint angle to, e.g. pi/16, works. Changing the planner from cartesian to joint space will fix the issue as well.
