### ISSUE TITLE
Connect: report non-compatible pairs as failures

### ISSUE THREAD

**Issue by rhaschke** [ros-planning/moveit_task_constructor#201]

**Comment by v4hn** [comment]
This should be optional, because there will usually be *many* failing pairs.
We could try to filter the failure reasons and only report each reason (except for numeric changes) once.

This has to be implemented around [here](https://github.com/ros-planning/moveit_task_constructor/blob/master/core/src/stage.cpp#L714)

**Comment by v4hn** [comment]
duplicate of #49
