### ISSUE TITLE
ComputeIk sometimes fails to check collision  

### ISSUE THREAD

**Issue by JonasTietz** [ros-planning/moveit_task_constructor#209]
Hello,
I have noticed that sometimes the solutions of the ComputeIk node are definitely in collision but get reported as success.

![ik_bug](https://user-images.githubusercontent.com/17435797/94021218-4ce82400-fda3-11ea-9c31-eb74a683f506.png)

For me it is not a big problem right now, because the collision gets detected once a trajectory is planned to that pose.

**Comment by rhaschke** [comment]
This is weird. Haven't noticed this before. Can you provide a minimal failing example for further debugging, please?

**Comment by v4hn** [comment]
This might be related to the robot models. I have seen this issue in the past as well with the same robot model (our custom PR2), but did not get a minimal example to work.
It seems that collision checking fails under some circumstances for the elbow meshes and primitive cubes.

As @JonasTietz also states, this is not safety-critical because the surrounding stages will reject this state as start/end of a trajectory, so I did not investigate too much yet.

**Comment by rhaschke** [comment]
If the collision is detected by the surrounding stage in the exactly same start/end state, we do have a bug. 
If the collision is only detected after some additional robot motion, the issue is probably due to your meshes as Michael suggested.
So, I would leave it as a task for @JonasTietz to validate which of those two situations we have at hand.

**Comment by v4hn** [comment]
Of course he is free to inspect further ;) but he should also get on with his actual research topic. :)

Either way there is an issue.

**Comment by Schteve-Bastian** [comment]
I'm encountering the same issue. IK plans through our container, but generally the following stages are unable to plan to/from the collision state.
![image](https://user-images.githubusercontent.com/65241498/130096704-a7803603-b102-4994-836c-8c7ef76efdee.png)
