### ISSUE TITLE
Pruning across container boundaries

### ISSUE THREAD

**Issue by v4hn** [ros-planning/moveit_task_constructor#247]
In #221 we implemented correct pruning of infeasible candidate solutions inside SerialContainers.

However, this does not work across container boundaries yet because Containers currently act as opaque stages in their parent.

Consider this example structure:

![rect2643](https://user-images.githubusercontent.com/680358/112162753-a44d3c80-8bec-11eb-9a04-50be71d6ae7b.png)

Assuming InterfaceState `a` fails to extend in Stage `Back`, `Fwd2` does not have to compute  InterfaceState `b` and the state can be disabled.
The same is true for the inverted case.

Parallel containers can result in similar situations but have to consider alternative paths through the different children as well.

I believe this is what you meant in https://github.com/ros-planning/moveit_task_constructor/pull/221#issuecomment-804847964 @rhaschke ?

**Comment by rhaschke** [comment]
Yes, that's definitely an open issue. I think, the other way around, i.e. a failing InterfaceState inside der container isn't yet propagated to the outside either.

**Comment by rhaschke** [comment]
I think we need to rethink the propagation of the `Interface::Status` for pruning once again: Currently, propagation occurs along connected solutions, neglecting the type of stage owning the `Interface`. Thus, currently, we cannot propagate through `Connect` stages, if their solutions are not yet connected. However, here pruning would be particularly beneficial, because we can rule out many opposite InterfaceStates. I think, status propagation should be handled by the (private?) stage classes.

Also, in order to allow propagation from inside containers to the outside, containers need to hook into their children's Interface to get notified on Status changes. This is currently not possible either.
